import type { Metadata } from "next";
// @ts-ignore: allow side-effect import of global CSS without type declarations
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-base-300 flex min-h-screen items-center justify-center font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
